package lwjglview.graphics.shader;

public enum ShaderType {
	CHIT_SHADER,
	TILE_SHADER,
	BACKGROUND_SHADER,
	ORTHO_SHADER,
	TARGET_SHADER,
	SELECTION_SHADER,
	TILE_SELECTION_SHADER,
	MENU_SELECTION_SHADER
}
