package controlview.enums;

public enum KeyType {
	ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, ZERO,
	Q, W, E, R, T, Y, U, I, O, P,
	A, S, D, F, G, H, J, K, L,
	Z, X, C, V, B, N, M,
	TICK, TAB, SHIFT, CTRL, SUPER, ALT, ENTER, ESCAPE,
	HOME, END, PGUP, PGDOWN, UP, DOWN, RIGHT, LEFT,
	MINUS, EQUAL, COMMA, PERIOD, COLON, QUOTE,
	OPENBRACKET, CLOSEBRACKET,
	FORWARDSLASH, BACKSLASH
}
